---

- name: stop the scheduled task
  ansible.windows.win_shell: schtasks /End /TN "Jenkins JNLP"

- name: wait till the task has stopped
  community.windows.win_scheduled_task_stat:
    name: "Jenkins JNLP"
  register: jenkins_node_jnlp_win_task_stat_stop
  until: jenkins_node_jnlp_win_task_stat_stop.state is defined and jenkins_node_jnlp_win_task_stat_stop.state.status == "Ready"
  retries: 10
  delay: 5

- name: start the scheduled task
  ansible.windows.win_shell: schtasks /Run /TN "Jenkins JNLP"

- name: wait till the task has started
  community.windows.win_scheduled_task_stat:
    name: "Jenkins JNLP"
  register: jenkins_node_jnlp_win_task_stat_start
  until: jenkins_node_jnlp_win_task_stat_start.state is defined and jenkins_node_jnlp_win_task_stat_start.state.status == "Running"
  retries: 10
  delay: 5
